### ISSUE TITLE
Runtime "undefined" even if I run node js runtime

### ISSUE THREAD

**Issue by moseseth** [arabold/serverless-test-plugin#2]
//index.js

`BbPromise.each(functions,
 function(functionData) {
                    let functionTestSuite = junitWriter.addTestsuite(functionData._config.sPath);
                    count++;
                                // I need to explicitly define it to make the tests running otherwise they are all skipped //
                                         functionData.runtime = "nodejs";
                    if (functionData.runtime === "nodejs") {`

**Comment by arabold** [comment]
Hi @moseseth , sorry for the lack of feedback. I'm not exactly sure what problem you're referring to here. I've updated the plugin to v0.2.0 yesterday which finally adds support for serverless v0.5.x and has some fixes for use with newer node runtimes. Does that help?

**Comment by moseseth** [comment]
Sure, thanks!
