### ISSUE TITLE
tests exit before the end without failing

### ISSUE THREAD

**Issue by AdrienLemaire** [arabold/serverless-test-plugin#6]
Considering the following function handler

```
const lib = require('../../lib/users_handlers');

module.exports.handler =
  (event, context) => {
    if (event.httpMethod === 'GET') {
      lib.getAttributeHandler(event, 'email', context.done);
    } else if (event.httpMethod === 'POST') {
      lib.setAttributeHandler(event, 'email', context.done);
    }
  };
```

and the event.json as follow

```
{ stage: 'dev', email: 'text@example.com' }
```

Since I forgot to set `httpMethod` in my event.json, the function never enters the if/else condition, and serverless-test-plugin stops running tests there.

In my case, the problem was due to a missing `context.fail('wrong_http_method');` at the end of my handler.
But I believe serverless-test-plugin should handle no-results cases as errors and continue running other functions tests. What do you think ?

**Comment by arabold** [comment]
It's a good point, yes. I'll look into it.

**Comment by arabold** [comment]
Took me a bit longer than anticipated. Sorry! But now functions should properly time out if you forget to invoke `context.done()` or the callback function. Let me know.
